(()=>{
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const owner=()=>localStorage.getItem('radMasteryOwnerPreview')==='true';
const localKey='radm-v12-forum';
const local=()=>JSON.parse(localStorage.getItem(localKey)||'[]');
const save=v=>localStorage.setItem(localKey,JSON.stringify(v));
const demo=[
{id:'d1',category:'registry-prep',title:'How do you review missed mock-exam questions?',body:'I started writing one sentence explaining why each wrong option is wrong. It has helped more than rereading the same chapter.',created_at:new Date(Date.now()-7200000).toISOString(),profiles:{display_name:'Graduate Member',student_status:'graduate'},solved:false,user_id:'demo'},
{id:'d2',category:'physics',title:'Inverse square law finally clicked for me',body:'I picture intensity spreading over a larger area as distance increases. Does anyone have another way they remember the squared relationship?',created_at:new Date(Date.now()-14400000).toISOString(),profiles:{display_name:'Current Student',student_status:'current'},solved:true,user_id:'demo'}];
function ago(iso){const n=(Date.now()-new Date(iso))/1000;if(n<60)return`${Math.max(1,n|0)}s ago`;if(n<3600)return`${(n/60)|0}m ago`;if(n<86400)return`${(n/3600)|0}h ago`;return`${(n/86400)|0}d ago`;}
async function posts(category){if(window.RRM_CLOUD?.user){try{return await window.RRM_CLOUD.listPosts(category)}catch(e){console.warn(e)}}return [...local(),...demo].filter(p=>category==='all'||p.category===category);}
async function attachment(p){if(!p.attachment_path)return'';if(window.RRM_CLOUD?.user){const url=await window.RRM_CLOUD.attachmentUrl(p.attachment_path);if(url)return p.attachment_path.toLowerCase().endsWith('.pdf')?`<a class="attachment-link" href="${esc(url)}" target="_blank" rel="noopener">Open attached PDF</a>`:`<img class="community-image" src="${esc(url)}" alt="Student uploaded notes or homework">`;}return'';}
async function card(p){const r=window.RRM_CLOUD?.user?await window.RRM_CLOUD.helpful(p.id).catch(()=>({count:0,mine:false})):{count:0,mine:false};const a=await attachment(p);const status=p.profiles?.student_status==='graduate'?'Graduate':'Current student';return`<article class="community-post panel" data-post-id="${esc(p.id)}"><div class="post-meta"><div class="avatar-small">${esc((p.profiles?.display_name||'R')[0])}</div><div><strong>${esc(p.profiles?.display_name||'Rad Mastery Member')}</strong><small>${status} · ${esc(p.category)} · ${ago(p.created_at)}</small></div>${p.solved?'<span class="solved-badge">Solved</span>':''}</div><h3>${esc(p.title)}</h3><p>${esc(p.body)}</p>${a}<div class="post-actions"><button class="reaction-btn helpful-v12 ${r.mine?'active':''}" data-id="${p.id}">Helpful <span>${r.count}</span></button><button class="reaction-btn replies-v12" data-id="${p.id}">Replies</button><button class="reaction-btn bookmark-v12" data-id="${p.id}">Save</button>${window.RRM_CLOUD?.user?.id===p.user_id?`<button class="reaction-btn solved-v12" data-id="${p.id}">${p.solved?'Reopen':'Mark solved'}</button>`:`<button class="reaction-btn report-v12" data-id="${p.id}">Report</button>`}</div><div class="discussion-panel" id="thread-${p.id}" hidden></div></article>`;}
async function render(target,category){const el=$(target);if(!el)return;el.innerHTML='<div class="panel"><p>Loading…</p></div>';const list=await posts(category);if(!list.length){el.innerHTML='<div class="panel"><p>No posts here yet. Start the first discussion.</p></div>';return;}const html=[];for(const p of list)html.push(await card(p));el.innerHTML=html.join('');bind(el);}
async function thread(id){const panel=$(`#thread-${CSS.escape(id)}`);if(!panel)return;if(!panel.hidden){panel.hidden=true;return;}panel.hidden=false;if(!window.RRM_CLOUD?.user){panel.innerHTML='<p class="microcopy">Sign in to reply. Owner preview can test the interface without publishing.</p>';return;}panel.innerHTML='<p class="microcopy">Loading replies…</p>';const replies=await window.RRM_CLOUD.listReplies(id).catch(()=>[]);panel.innerHTML=`<div class="comment-list">${replies.length?replies.map(r=>`<div class="comment"><strong>${esc(r.profiles?.display_name||'Member')}</strong><small>${ago(r.created_at)}</small><p>${esc(r.body)}</p>${r.is_solution?'<span class="solved-badge">Solution</span>':''}</div>`).join(''):'<p class="microcopy">No replies yet.</p>'}</div><form class="comment-form"><input maxlength="1000" required placeholder="Write a helpful reply…"><button class="btn btn-small">Reply</button></form>`;panel.querySelector('form').onsubmit=async e=>{e.preventDefault();const v=e.currentTarget.querySelector('input').value.trim();if(!v)return;await window.RRM_CLOUD.reply(id,v);panel.hidden=true;await thread(id);};}
function bind(root){root.querySelectorAll('.replies-v12').forEach(b=>b.onclick=()=>thread(b.dataset.id));root.querySelectorAll('.helpful-v12').forEach(b=>b.onclick=async()=>{if(!window.RRM_CLOUD?.user)return alert('Sign in to react.');await window.RRM_CLOUD.toggleHelpful(b.dataset.id);refreshAll();});root.querySelectorAll('.bookmark-v12').forEach(b=>b.onclick=async()=>{if(!window.RRM_CLOUD?.user)return alert('Sign in to save posts.');await window.RRM_CLOUD.toggleBookmark(b.dataset.id);b.textContent='Saved';});root.querySelectorAll('.solved-v12').forEach(b=>b.onclick=async()=>{const post=(await window.RRM_CLOUD.listPosts('all')).find(p=>p.id===b.dataset.id);await window.RRM_CLOUD.markSolved(b.dataset.id,!post?.solved);refreshAll();});root.querySelectorAll('.report-v12').forEach(b=>b.onclick=async()=>{if(!window.RRM_CLOUD?.user)return alert('Sign in to report a post.');await window.RRM_CLOUD.reportPost(b.dataset.id);b.textContent='Reported';});}
async function create(category,title,body,file,msgEl){if(window.RRM_CLOUD?.user){await window.RRM_CLOUD.createPost({category,title,body,file});}else if(owner()){const arr=local();arr.unshift({id:crypto.randomUUID(),user_id:'owner-preview',category,title,body,attachment_path:null,created_at:new Date().toISOString(),profiles:{display_name:'Owner Preview',student_status:'current'},solved:false});save(arr);}else throw new Error('Sign in to post.');if(msgEl)msgEl.textContent=window.RRM_CLOUD?.user?'Posted successfully.':'Preview post added locally.';await refreshAll();}
$('#notesFile')?.addEventListener('change',e=>{const f=e.target.files[0];$('#notesFileName').textContent=f?`${f.name} · ${(f.size/1048576).toFixed(1)} MB`:'';if(f&&f.size>10*1024*1024){alert('Maximum file size is 10 MB.');e.target.value='';$('#notesFileName').textContent='';}});
$('#notesHelpForm')?.addEventListener('submit',async e=>{e.preventDefault();const m=$('#notesHelpMessage');try{const f=$('#notesFile').files[0]||null;if(f&&!['image/jpeg','image/png','image/webp','application/pdf'].includes(f.type))throw new Error('Use JPG, PNG, WEBP, or PDF only.');await create('notes-help',$('#notesTitle').value.trim(),$('#notesBody').value.trim(),f,m);e.target.reset();$('#notesFileName').textContent='';}catch(err){m.textContent=err.message;}});
$('#tipForm')?.addEventListener('submit',async e=>{e.preventDefault();const m=$('#tipMessage');try{await create('tips-tricks',$('#tipTitle').value.trim(),$('#tipBody').value.trim(),null,m);e.target.reset();}catch(err){m.textContent=err.message;}});
$('#forumForm')?.addEventListener('submit',async e=>{e.preventDefault();const m=$('#forumMessage');try{await create($('#forumCategory').value,$('#forumTitle').value.trim(),$('#forumBody').value.trim(),null,m);e.target.reset();}catch(err){m.textContent=err.message;}});
$('#forumFilter')?.addEventListener('change',e=>render('#forumFeed',e.target.value));
document.querySelectorAll('[data-refresh-feed]').forEach(b=>b.onclick=()=>refreshAll());
async function refreshAll(){await Promise.all([render('#notesHelpFeed','notes-help'),render('#tipsFeed','tips-tricks'),render('#forumFeed',$('#forumFilter')?.value||'all')]);}
setTimeout(refreshAll,350);
})();
