(function(){
 const $=s=>document.querySelector(s);
 window.v19Studio=function(lesson){
  const key='rrm-v19-'+lesson.id, saved=JSON.parse(localStorage.getItem(key)||'{}');
  return `<section class="mastery-studio" data-v19="${lesson.id}"><p class="eyebrow">Active Learning Studio</p><h3>Don't just read it — prove you can use it</h3><div class="studio-grid"><div class="studio-card"><strong>Teach it back</strong><p>Explain ${lesson.title.toLowerCase()} as if you were teaching a first-semester student.</p><textarea class="teachback" rows="4" placeholder="Explain the mechanism without looking back…">${saved.teach||''}</textarea></div><div class="studio-card"><strong>Confidence calibration</strong><p>How confidently could you answer a new application question?</p><div class="confidence-row">${[1,2,3,4,5].map(n=>`<button type="button" data-confidence="${n}" class="${saved.conf==n?'selected':''}">${n}</button>`).join('')}</div><div class="microchallenge"><b>Retrieval prompt:</b> Name the single variable or mechanism in this lesson most likely to become a registry distractor.</div></div><div class="studio-card"><strong>Clinical transfer</strong><p>Write one way this concept changes what you do at the tube, detector, console, bedside, or fluoroscopy unit.</p><textarea class="clinical" rows="3" placeholder="In practice, this matters because…">${saved.clinical||''}</textarea></div><div class="studio-card"><strong>Scratch calculation / prediction</strong><p>Before touching a control, predict the direction of change. Then verify it in the simulator or lesson rationale.</p><input class="prediction" value="${saved.pred||''}" placeholder="My prediction…"></div></div></section>`;
 };
 window.wireV19Studio=function(lesson){const root=document.querySelector(`[data-v19="${lesson.id}"]`);if(!root)return;const save=()=>localStorage.setItem('rrm-v19-'+lesson.id,JSON.stringify({teach:root.querySelector('.teachback').value,clinical:root.querySelector('.clinical').value,pred:root.querySelector('.prediction').value,conf:+(root.querySelector('[data-confidence].selected')?.dataset.confidence||0)}));root.querySelectorAll('textarea,input').forEach(x=>x.addEventListener('input',save));root.querySelectorAll('[data-confidence]').forEach(b=>b.onclick=()=>{root.querySelectorAll('[data-confidence]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');save()})};
 window.v19TechniqueLab=function(lesson){if(!/kVp|mAs|exposure factors|technique/i.test(lesson.title))return '';return `<section class="technique-lab-v19"><p class="eyebrow">Acquisition Lab</p><h3>Technique → detector exposure → image appearance</h3><div class="labgrid"><div class="xray-wrap" id="v19xray"><img src="assets/verified_real/hand-pa-cc0.jpg" alt="PA hand radiograph teaching image"><div class="xray-noise"></div></div><div class="lab-controls"><label>kVp <b id="v19kout">70</b><input id="v19k" type="range" min="45" max="95" value="70"></label><label>mAs <b id="v19mout">5.0</b><input id="v19m" type="range" min="1" max="12" step=".5" value="5"></label><div class="metric-grid"><div>Relative receptor exposure<br><b id="v19exp">1.00×</b></div><div>Quantum noise<br><b id="v19noise">Reference</b></div><div>Penetration<br><b id="v19pen">Reference</b></div><div>Subject contrast trend<br><b id="v19con">Reference</b></div></div><p id="v19teach">Move one factor at a time and explain why the image changes.</p><div class="challenge-box"><b>Challenge:</b> SID changes from 40″ to 72″. Starting at 5 mAs, what mAs maintains receptor exposure? <input id="v19ans" inputmode="decimal"><button type="button" id="v19check">Check</button><span id="v19feedback"></span></div></div></div></section>`};
 window.wireV19Technique=function(){const k=$('#v19k'),m=$('#v19m');if(!k||!m)return;const u=()=>{const kv=+k.value,ma=+m.value;$('#v19kout').textContent=kv;$('#v19mout').textContent=ma.toFixed(1);const exp=(ma/5)*Math.pow(kv/70,2);const noise=Math.min(.65,.18/Math.sqrt(Math.max(.12,exp)));const b=.82+Math.min(1.5,exp)*.16;const c=1.5-(kv-45)/100;$('#v19xray').style.setProperty('--b',b);$('#v19xray').style.setProperty('--c',c);$('#v19xray').style.setProperty('--n',noise);$('#v19exp').textContent=exp.toFixed(2)+'×';$('#v19noise').textContent=exp<.65?'Increased':exp>1.6?'Low (but excess exposure)':'Reference';$('#v19pen').textContent=kv<60?'Reduced':kv>82?'Increased':'Reference';$('#v19con').textContent=kv<60?'Higher':kv>82?'Lower':'Reference';$('#v19teach').textContent=exp<.65?'Low receptor exposure increases quantum noise. Digital processing may rescale brightness, so noise and exposure indicators matter.':exp>1.6?'High receptor exposure can still produce an acceptable-looking digital image. That is why exposure creep is dangerous.':kv>82?'Higher kVp increases penetration and tends to reduce subject contrast; technique must be balanced with dose and receptor exposure.':'Change one factor at a time, predict first, then observe.'};k.oninput=u;m.oninput=u;u();$('#v19check').onclick=()=>{const a=+$('#v19ans').value,correct=5*Math.pow(72/40,2);$('#v19feedback').textContent=Math.abs(a-correct)<.2?' Correct — 16.2 mAs.':' Recheck the exposure maintenance formula: mAs₂ = mAs₁ × (SID₂/SID₁)².'}}
})();
