(function(){
window.V20_AUDIO={
 'radiation-physics-07':'https://www.aidocmaker.com/g0/audio?name=b41e729d09f8454ba8c62e824be0a0e4',
 'radiation-physics-08':'https://www.aidocmaker.com/g0/audio?name=9814c8e8eba34f4d82edcfc0ae3a4074',
 'radiation-physics-09':'https://www.aidocmaker.com/g0/audio?name=28526e9866dd403395d0f68f526a23de',
 'radiation-physics-10':'https://www.aidocmaker.com/g0/audio?name=5be38084c3e4494dbafa1e4b868ea80d',
 'radiation-physics-12':'https://www.aidocmaker.com/g0/audio?name=606b66a9608a41e886eb7bb3a2e281d6'
};
const circuitQs=[
 {category:'Radiation Physics',q:'In the primary circuit, which component permits the operator-selected kVp to vary the voltage supplied to the primary winding of the high-voltage transformer?',options:['Autotransformer','Step-down filament transformer','Full-wave rectifier bank','Rotor-stator assembly'],answer:0,explanation:'The autotransformer is on the primary side and provides a selectable voltage to the primary winding of the high-voltage transformer. The filament transformer controls filament current, rectifiers enforce one-way tube current, and the rotor-stator drives anode rotation.'},
 {category:'Radiation Physics',q:'After the autotransformer and exposure-control section, which component produces the large potential difference required to accelerate electrons from cathode to anode?',options:['Step-up high-voltage transformer','Step-down filament transformer','Line compensator','Focusing cup'],answer:0,explanation:'The high-voltage transformer steps voltage up to the kilovoltage range. Its secondary current correspondingly decreases according to transformer relationships.'},
 {category:'Radiation Physics',q:'Why is rectification required in the high-voltage circuit of an x-ray unit?',options:['To keep tube current flowing from cathode toward anode','To increase filament current before thermionic emission','To select the focal spot size','To stabilize incoming line voltage'],answer:0,explanation:'The x-ray tube behaves as a diode. Rectification prevents reverse tube current and maintains electron flow from the negative cathode toward the positive anode during exposure.'},
 {category:'Radiation Physics',q:'Which transformer is designed to deliver low voltage and relatively high current to the tungsten filament?',options:['Step-down filament transformer','Step-up high-voltage transformer','Autotransformer','Isolation transformer in the secondary high-voltage circuit'],answer:0,explanation:'The filament transformer steps voltage down and current up so the filament can be heated sufficiently for thermionic emission.'},
 {category:'Radiation Physics',q:'A technologist increases mA while kVp is unchanged. Which circuit action most directly supports the increase in tube current?',options:['More filament heating increases the available space-charge electron cloud','The high-voltage transformer increases its turns ratio','Rectifiers reverse the direction of electron flow','The rotor decreases anode speed'],answer:0,explanation:'Higher mA requires more electrons crossing the tube per unit time. Increasing filament current raises filament temperature and thermionic emission, increasing electron availability.'},
 {category:'Radiation Physics',q:'Which sequence best represents the high-voltage path that establishes tube potential during an exposure?',options:['Autotransformer → high-voltage transformer → rectification → x-ray tube','Filament transformer → autotransformer → stator → x-ray tube','Rectifiers → autotransformer → filament transformer → anode','High-voltage transformer → line compensator → filament → rotor'],answer:0,explanation:'Conceptually, selected primary voltage from the autotransformer feeds the high-voltage transformer; the secondary high voltage is rectified and applied across the x-ray tube.'},
 {category:'Radiation Physics',q:'The focusing cup is electrically negative primarily so that it can:',options:['Electrostatically narrow the electron cloud toward the focal spot','Increase target rotation speed','Rectify secondary voltage','Raise the binding energy of tungsten target atoms'],answer:0,explanation:'The negatively charged focusing cup repels and confines emitted electrons, directing them toward the focal spot on the anode.'},
 {category:'Radiation Physics',q:'Which statement correctly distinguishes the rotor and stator?',options:['The rotor is inside the tube envelope and turns the anode; the stator is outside the envelope and creates the rotating magnetic field','The stator is inside the envelope and emits electrons; the rotor is outside and rectifies current','Both are located in the cathode assembly','Both directly determine selected kVp'],answer:0,explanation:'The induction motor uses external stator windings to create a rotating magnetic field that turns the internal rotor attached to the anode.'},
 {category:'Radiation Physics',q:'If the filament transformer failed open but the high-voltage circuit remained functional, the most direct consequence would be:',options:['Little or no thermionic emission and therefore little or no tube current','Uncontrolled increase in kVp','Reverse tube current through the rectifiers','Immediate increase in anode rotation speed'],answer:0,explanation:'Without filament heating, the cathode cannot supply the electron cloud needed for tube current even if a high potential difference is available.'},
 {category:'Radiation Physics',q:'Which component is physically part of the cathode assembly?',options:['Tungsten filament and focusing cup','Tungsten-rhenium focal track and rotor','Stator windings and rectifiers','Glass envelope and high-voltage transformer'],answer:0,explanation:'The cathode contains one or more filaments seated in a focusing cup. The focal track and rotor are associated with the anode.'}
];
questionBank.unshift(...circuitQs);
const physics=courseData.find(m=>m.module==='Radiation Physics');
if(physics){
 const find=(re)=>physics.lessons.find(l=>re.test(l.title));
 const circuit=find(/x-ray circuit/i); if(circuit){circuit.check=circuitQs.slice(0,5).map(x=>({q:x.q,options:x.options,answer:x.answer,rationale:x.explanation}));circuit.content += `<section class="v20-depth"><h3>Trace the x-ray circuit as a system</h3><p>Do not memorize a disconnected list of components. Follow the job performed at each stage. Incoming electrical power is conditioned, the operator-selected kVp is established on the primary side, exposure timing controls energization, the high-voltage transformer creates the potential difference needed across the tube, rectification maintains the correct polarity, and the tube converts electron kinetic energy into heat and x-ray photons.</p><ol><li><b>Line compensation:</b> stabilizes incoming line voltage before technique selection.</li><li><b>Autotransformer:</b> provides a selectable primary voltage and is associated with kVp selection.</li><li><b>Exposure switch/timer:</b> controls when and how long the exposure circuit is energized.</li><li><b>High-voltage transformer:</b> steps voltage up dramatically; current changes inversely in an ideal transformer.</li><li><b>Rectification:</b> prevents reverse tube current so electrons travel cathode → anode.</li><li><b>X-ray tube:</b> converts electron kinetic energy predominantly to heat, with a small fraction producing x-rays.</li></ol><p><b>Registry distinction:</b> the filament circuit and high-voltage circuit solve different problems. The filament circuit supplies electron availability; the high-voltage circuit supplies electron acceleration.</p></section>`; circuit.interactive='circuit-builder';}
 const trans=find(/Transformers/i); if(trans) trans.check=circuitQs.slice(0,5).map(x=>({q:x.q,options:x.options,answer:x.answer,rationale:x.explanation}));
 const cath=find(/Thermionic emission/i); if(cath){cath.check=circuitQs.slice(4,9).map(x=>({q:x.q,options:x.options,answer:x.answer,rationale:x.explanation}));cath.content += `<section class="v20-depth"><h3>Cathode assembly: from filament current to tube current</h3><p>The cathode is the negative electrode. Its filament is heated by a low-voltage, high-current circuit. As filament temperature rises, electrons gain enough thermal energy to escape the tungsten surface and form a space-charge cloud. The focusing cup confines that cloud so that, when the high-voltage potential is applied, electrons are driven toward a controlled area of the anode focal track.</p><p><b>Do not confuse:</b> filament current heats the filament; tube current is the electron flow across the tube during exposure. They are related, but they are not the same current.</p></section>`;}
 const tube=find(/tube components|x-ray tube/i); if(tube) tube.content += `<section class="v20-depth"><h3>Component-by-component tube anatomy</h3><p><b>Cathode:</b> negative electrode containing filament(s) and focusing cup. <b>Anode:</b> positive electrode containing the target/focal track; in rotating-anode tubes it is attached to the rotor. <b>Stator:</b> external electromagnets that induce rotor rotation. <b>Envelope:</b> maintains the vacuum needed for efficient electron travel. <b>Protective housing:</b> provides electrical/mechanical protection and limits leakage radiation. <b>Tube window:</b> the path designed for the useful beam to leave the tube assembly with less attenuation.</p></section>`;
}
flashcards.unshift(
 {category:'Radiation Physics',front:'Circuit order: what follows the autotransformer on the exposure/high-voltage path?',back:'Exposure-control/timing section → high-voltage step-up transformer → rectification → x-ray tube.'},
 {category:'Radiation Physics',front:'Filament transformer: step-up or step-down?',back:'Step-down voltage, step-up current. Its job is to heat the filament for thermionic emission.'},
 {category:'Radiation Physics',front:'Focusing cup function',back:'Negatively charged cathode component that electrostatically narrows/directs the electron cloud toward the focal spot.'},
 {category:'Radiation Physics',front:'Rotor vs stator',back:'Rotor: inside envelope, attached to anode. Stator: outside envelope, creates rotating magnetic field.'},
 {category:'Radiation Physics',front:'Why rectify the high-voltage circuit?',back:'To maintain correct tube polarity and prevent reverse electron flow; tube current should travel cathode → anode.'}
);
})();
