(function(){
window.V22=true;
const subjectScenes={
 'Radiation Physics':['Electron source','Acceleration','Target interaction','X-ray photon'],
 'Image Production':['Technique selection','Photon beam','Patient attenuation','Remnant beam','Detector exposure'],
 'Digital Imaging':['X-ray absorption','Conversion','Charge signal','ADC / processing','Displayed pixel'],
 'Fluoroscopy':['X-ray tube','Patient','Scatter','Detector','Real-time display'],
 'Radiation Safety':['Source','Collimation','Patient','Scatter field','Shield / distance'],
 'Positioning & Procedures':['Patient position','Part alignment','Central ray','IR','Image evaluation'],
 'Patient Care & Clinical':['Assess','Prepare','Perform safely','Monitor','Reassess'],
 'Registry Strategy':['Read stem','Find variable','Apply mechanism','Eliminate distractors','Commit answer']
};
function addMediaDepth(){
 courseData.forEach(mod=>mod.lessons.forEach((l,idx)=>{
   l.v21Subject=mod.module;
   l.v22Steps=subjectScenes[mod.module]||['Input','Mechanism','Outcome'];
   // Guarantee a meaningful reading structure beyond a card-sized paragraph.
   if((l.content||'').length<2200){
     const title=l.title;
     l.content=(l.content||'')+`<section class="v22-depth"><h3>Mechanism map: ${title}</h3><p>Study this topic as a sequence rather than an isolated definition. Identify the input, the component or interaction that changes it, and the measurable consequence. Then connect that consequence to image quality, receptor exposure, patient dose, geometry, or clinical safety as appropriate.</p><h3>What to recognize on the registry</h3><p>Expect distractors that are factually related but belong to a different part of the imaging chain. Ask which variable changed first, then follow that change forward one step at a time. When digital processing is involved, keep acquisition exposure separate from displayed brightness.</p><h3>Clinical transfer</h3><p>Before repeating an image or changing technique, identify the actual failure mode. Decide whether the problem is penetration, photon quantity/noise, scatter, geometry, motion, positioning, processing, artifact, or patient condition. Correct the cause rather than the appearance alone.</p><h3>Teach-back checkpoint</h3><p>At the end of this lesson, you should be able to explain the mechanism without looking at the page, identify one common registry trap, and predict what happens when the controlling variable is increased, decreased, omitted, or misaligned.</p></section>`;
   }
 }));
 // Map key physics lessons to purpose-built labs.
 const p=courseData.find(x=>x.module==='Radiation Physics'); if(p){
   p.lessons.forEach(l=>{if(/thermionic|cathode/i.test(l.title))l.interactive='v22-cathode'; if(/circuit/i.test(l.title))l.interactive='v22-circuit'; if(/brems|characteristic|x-ray production/i.test(l.title))l.interactive='v22-particles';});
 }
 const im=courseData.find(x=>x.module==='Image Production'); if(im){im.lessons.forEach(l=>{if(/kvp|mas|technique|exposure/i.test(l.title))l.interactive='v22-technique';});}
}
addMediaDepth();

window.v22Studio=function(lesson){
 const steps=lesson.v22Steps||['Input','Mechanism','Outcome'];
 return `<section class="v22-studio"><div class="v22-head"><span class="premium-label">ANIMATED MECHANISM</span><strong>${lesson.v21Subject||''}</strong></div><div class="v22-flow">${steps.map((s,i)=>`<div class="v22-step" style="--i:${i}"><i></i><span>${s}</span></div>`).join('<b class="v22-arrow">→</b>')}</div><div class="v22-playbar"><button type="button" class="btn v22-replay">▶ Replay animation</button><button type="button" class="btn btn-secondary v22-slow">½× Slow motion</button></div></section>`;
};
window.v22Interactive=function(type){
 if(type==='v22-cathode') return `<section class="v22-lab"><h3>Cathode & thermionic emission lab</h3><p>Move filament current. Watch filament heat and the conceptual space-charge electron population respond.</p><label>Filament current <strong id="v22FilVal">50%</strong><input id="v22Fil" type="range" min="0" max="100" value="50"></label><div class="v22-cathode"><div class="v22-cup"><div id="v22Filament" class="v22-filament"></div></div><div id="v22Cloud" class="v22-cloud"></div><div class="v22-target">ANODE</div></div><div id="v22FilRead" class="lesson-callout">Moderate heating → moderate thermionic emission.</div></section>`;
 if(type==='v22-technique') return `<section class="v22-lab"><h3>kVp / mAs image-production lab</h3><p>Both sliders update immediately. This is a teaching simulation: displayed brightness is normalized to emphasize why digital brightness alone is not an exposure indicator.</p><div class="v22-techgrid"><div><label>kVp <strong id="v22KVal">70</strong><input id="v22K" type="range" min="45" max="110" value="70"></label><label>mAs <strong id="v22MVal">5</strong><input id="v22M" type="range" min="1" max="20" step=".5" value="5"></label><div id="v22Metrics"></div></div><div class="v22-hand"><img id="v22Hand" src="assets/verified_real/hand-pa-cc0.jpg" alt="Hand radiograph teaching image"><div id="v22Noise" class="v22-noise"></div></div></div></section>`;
 if(type==='v22-particles') return `<section class="v22-lab"><h3>Electron & photon atomic-view animation</h3><div class="v22-particle-stage"><div class="v22-nucleus">W<br><small>nucleus</small></div><i class="v22-electron">e−</i><i class="v22-photon">X-RAY</i><div class="v22-shell s1"></div><div class="v22-shell s2"></div></div><div class="v22-modebar"><button data-pmode="brems">Bremsstrahlung</button><button data-pmode="characteristic">Characteristic</button><button data-pmode="compton">Compton</button><button data-pmode="photoelectric">Photoelectric</button></div><div id="v22ParticleText" class="lesson-callout">Select a mechanism, then watch the electron/photon path and read the energy-transfer explanation.</div></section>`;
 if(type==='v22-circuit') return `<section class="v22-lab"><h3>Interactive X-ray circuit layout</h3><p>Tap each numbered component. Follow the primary/high-voltage path and the separate filament branch.</p><div class="v22-circuit"><div class="cnode" data-c="Incoming AC / line compensation stabilizes supply before technique selection.">1<br>AC / LINE</div><span>→</span><div class="cnode" data-c="Autotransformer provides selectable primary voltage and is associated with kVp selection.">2<br>AUTO</div><span>→</span><div class="cnode" data-c="Exposure control / timer determines when and how long the circuit is energized.">3<br>TIMER</div><span>→</span><div class="cnode" data-c="Step-up transformer creates the high potential difference applied across the tube.">4<br>STEP-UP</div><span>→</span><div class="cnode" data-c="Rectifiers maintain proper tube polarity and prevent reverse tube current.">5<br>RECTIFY</div><span>→</span><div class="cnode" data-c="X-ray tube accelerates electrons cathode to anode; target interactions create heat and x-rays.">6<br>X-RAY TUBE</div><div class="cbranch">↘ FILAMENT BRANCH → <button class="cnode" data-c="Step-down filament transformer supplies low voltage and high current to heat the filament.">7 STEP-DOWN</button> → <button class="cnode" data-c="Heated filament releases electrons by thermionic emission; focusing cup directs the cloud.">8 FILAMENT / CUP</button></div></div><div id="v22CircuitText" class="lesson-callout">Start at component 1 and trace the system.</div></section>`;
 return '';
};

window.bindV22=function(lesson){
 document.querySelectorAll('.v22-replay').forEach(b=>b.onclick=()=>{const s=b.closest('.v22-studio');s.classList.remove('playing');void s.offsetWidth;s.classList.add('playing')});
 document.querySelectorAll('.v22-slow').forEach(b=>b.onclick=()=>b.closest('.v22-studio').classList.toggle('slow'));
 const f=document.getElementById('v22Fil'); if(f){const u=()=>{let v=+f.value;document.getElementById('v22FilVal').textContent=v+'%';document.getElementById('v22Filament').style.setProperty('--heat',v/100);document.getElementById('v22Cloud').style.setProperty('--cloud',v/100);document.getElementById('v22FilRead').textContent=v<30?'Low heating → few electrons escape → low electron availability.':v<70?'Moderate heating → a larger space-charge cloud forms near the cathode.':'High heating → strong thermionic emission → greater electron availability for tube current.'};f.oninput=u;u();}
 const k=document.getElementById('v22K'),m=document.getElementById('v22M'); if(k&&m){const u=()=>{let kv=+k.value,ma=+m.value;document.getElementById('v22KVal').textContent=kv;document.getElementById('v22MVal').textContent=ma;let exposure=(ma/5)*Math.pow(kv/70,2);let noise=Math.max(0.08,Math.min(.75,.52/Math.sqrt(Math.max(.2,exposure))));document.getElementById('v22Hand').style.filter=`contrast(${Math.max(.72,1.25-(kv-45)/160)}) brightness(${.92+Math.min(.15,exposure/20)})`;document.getElementById('v22Noise').style.opacity=noise;document.getElementById('v22Metrics').innerHTML=`<b>Relative receptor exposure:</b> ${exposure.toFixed(2)}×<br><b>Penetration:</b> ${kv<60?'low':kv<85?'moderate':'high'}<br><b>Quantum-noise risk:</b> ${exposure<.65?'high':exposure<1.3?'moderate':'low'}`};k.oninput=u;m.oninput=u;u();}
 document.querySelectorAll('[data-pmode]').forEach(b=>b.onclick=()=>{const st=b.closest('.v22-lab').querySelector('.v22-particle-stage');st.dataset.mode=b.dataset.pmode;void st.offsetWidth;st.classList.remove('run');requestAnimationFrame(()=>st.classList.add('run'));const txt={brems:'Bremsstrahlung: the projectile electron is deflected/decelerated in the nuclear electric field. Lost kinetic energy is emitted as an x-ray photon.',characteristic:'Characteristic: a projectile electron ejects an inner-shell electron. A higher-shell electron fills the vacancy; the binding-energy difference is emitted as a discrete x-ray photon.',compton:'Compton: the incoming photon transfers part of its energy to an outer-shell electron. A recoil electron and lower-energy scattered photon leave the interaction.',photoelectric:'Photoelectric: the incoming photon is completely absorbed and an inner-shell photoelectron is ejected.'};document.getElementById('v22ParticleText').textContent=txt[b.dataset.pmode];});
 document.querySelectorAll('[data-c]').forEach(n=>n.onclick=()=>{document.querySelectorAll('[data-c]').forEach(x=>x.classList.remove('active'));n.classList.add('active');document.getElementById('v22CircuitText').textContent=n.dataset.c});
};
})();
