(function(){
const SUBJECT_AUDIO={
 'Radiation Physics':'https://www.aidocmaker.com/g0/audio?name=d75c9a0a8039476b8eb53a46ef6c2953',
 'Image Production':'https://www.aidocmaker.com/g0/audio?name=de504a5adeca432491eb33d98a053494',
 'Digital Imaging':'https://www.aidocmaker.com/g0/audio?name=0343fe838d5649c1adc8be456badb6a9',
 'Fluoroscopy':'https://www.aidocmaker.com/g0/audio?name=1b6b2607c03640b4a778b6aa6019f357',
 'Radiation Safety & Biology':'https://www.aidocmaker.com/g0/audio?name=1d4a727cb40e41fcabf9f5a1e530526a',
 'Patient Care & Clinical':'https://www.aidocmaker.com/g0/audio?name=78756d8dc63d48b58e087bab597b6345',
 'Positioning & Procedures':'https://www.aidocmaker.com/g0/audio?name=4802ab78152341d5b7c1e337215a8495',
 'Registry Strategy':'https://www.aidocmaker.com/g0/audio?name=039a65bb474d40cdb34469665013b28e'
};
window.V25_SUBJECT_AUDIO=SUBJECT_AUDIO;

const styles=`
.v25-media{margin:22px 0;border:1px solid rgba(219,170,82,.25);background:linear-gradient(145deg,#0b0e14,#111722);border-radius:20px;overflow:hidden}.v25-media-head{display:flex;gap:14px;align-items:center;justify-content:space-between;padding:18px 20px;border-bottom:1px solid rgba(255,255,255,.08)}.v25-media-head h3{margin:4px 0 0}.v25-actions{display:flex;gap:8px;flex-wrap:wrap}.v25-stage{position:relative;min-height:330px;background:radial-gradient(circle at 50% 40%,rgba(78,126,255,.08),transparent 45%),#070a0e;overflow:hidden}.v25-stage *{box-sizing:border-box}.v25-caption{position:absolute;left:16px;right:16px;bottom:12px;background:rgba(0,0,0,.68);border:1px solid rgba(255,255,255,.12);padding:10px 12px;border-radius:12px;font-size:.9rem;z-index:8}.v25-legend{display:flex;gap:12px;flex-wrap:wrap;padding:10px 18px 16px;color:#c9ced8;font-size:.82rem}.v25-dot{display:inline-block;width:9px;height:9px;border-radius:50%;margin-right:5px}.v25-dot.e{background:#57a7ff}.v25-dot.p{background:#ffd24a}.v25-dot.s{background:#fd8c5a}.v25-media.playing .v25-electron{animation:v25electron 2.8s linear infinite}.v25-media.slow .v25-electron{animation-duration:6s}.v25-media.playing .v25-photon{animation:v25photon 2.2s linear infinite}.v25-media.slow .v25-photon{animation-duration:4.8s}@keyframes v25electron{0%{left:12%;opacity:0}10%{opacity:1}75%{left:72%;opacity:1}85%,100%{left:74%;opacity:0}}@keyframes v25photon{0%,56%{opacity:0;transform:translate(0,0) rotate(-12deg)}60%{opacity:1}100%{opacity:0;transform:translate(170px,90px) rotate(-12deg)}}
.v25-tube{position:absolute;left:7%;right:7%;top:64px;height:150px;border:2px solid #45505d;border-radius:75px;background:linear-gradient(90deg,rgba(255,127,44,.08),rgba(77,151,255,.04))}.v25-filament{position:absolute;left:12%;top:115px;width:56px;height:28px;border:5px solid #ff8b38;border-radius:50%;box-shadow:0 0 22px #ff7a20}.v25-target{position:absolute;right:20%;top:86px;width:28px;height:100px;background:linear-gradient(#d9a55c,#785127);transform:skew(-12deg);box-shadow:0 0 18px rgba(255,184,92,.35)}.v25-electron{position:absolute;left:12%;top:133px;width:12px;height:12px;background:#55a7ff;border-radius:50%;box-shadow:0 0 14px #55a7ff}.v25-electron.e2{animation-delay:.6s}.v25-electron.e3{animation-delay:1.2s}.v25-electron.e4{animation-delay:1.8s}.v25-photon{position:absolute;left:73%;top:128px;width:70px;height:3px;background:#ffd24a;box-shadow:0 0 10px #ffd24a;transform-origin:left}.v25-label{position:absolute;color:#d9dee7;font-size:.8rem}.v25-l1{left:9%;top:225px}.v25-l2{left:42%;top:225px}.v25-l3{right:15%;top:225px}
.v25-atom{position:absolute;width:200px;height:200px;left:50%;top:48%;transform:translate(-50%,-50%)}.v25-nucleus{position:absolute;width:74px;height:74px;left:63px;top:63px;border-radius:50%;background:radial-gradient(circle,#8f79ff,#32245a);display:grid;place-items:center;font-weight:800}.v25-shell{position:absolute;border:1px solid #5b6f94;border-radius:50%;inset:25px}.v25-shell.s2{inset:0}.v25-bound{position:absolute;width:10px;height:10px;background:#9cc4ff;border-radius:50%}.v25-b1{left:42px;top:74px}.v25-b2{right:34px;top:104px}.v25-incident{position:absolute;left:8%;top:48%;width:14px;height:14px;background:#55a7ff;border-radius:50%;box-shadow:0 0 15px #55a7ff}.v25-media.playing .v25-incident{animation:v25incident 2.8s ease-in-out infinite}@keyframes v25incident{0%{left:8%;top:48%;opacity:.2}55%{left:45%;top:48%;opacity:1}72%{left:59%;top:33%;opacity:1}100%{left:78%;top:20%;opacity:.2}}.v25-xray{position:absolute;left:56%;top:52%;width:90px;height:3px;background:#ffd24a;box-shadow:0 0 13px #ffd24a;opacity:0}.v25-media.playing .v25-xray{animation:v25xray 2.8s ease-out infinite}@keyframes v25xray{0%,58%{opacity:0;transform:scaleX(.1)}68%{opacity:1}100%{opacity:0;transform:translate(130px,45px) scaleX(1)}}
.v25-chain{display:flex;align-items:center;justify-content:center;gap:8px;position:absolute;inset:50px 20px 80px}.v25-box{min-width:110px;min-height:70px;border:1px solid #4b5a6e;border-radius:13px;padding:12px;display:grid;place-items:center;text-align:center;background:#101722;position:relative}.v25-arrow{font-size:1.5rem;color:#d8aa52}.v25-media.playing .v25-box{animation:v25pulse 4s ease-in-out infinite}.v25-media.playing .v25-box:nth-of-type(2){animation-delay:.6s}.v25-media.playing .v25-box:nth-of-type(3){animation-delay:1.2s}.v25-media.playing .v25-box:nth-of-type(4){animation-delay:1.8s}.v25-media.playing .v25-box:nth-of-type(5){animation-delay:2.4s}@keyframes v25pulse{0%,100%{border-color:#4b5a6e;transform:translateY(0)}30%{border-color:#d8aa52;box-shadow:0 0 18px rgba(216,170,82,.25);transform:translateY(-4px)}}
.v25-field{position:absolute;left:15%;right:15%;top:35px;bottom:80px}.v25-patient{position:absolute;left:40%;top:28%;width:20%;height:44%;border-radius:50% 50% 36% 36%;background:#273243;border:1px solid #7b8797}.v25-beam{position:absolute;left:19%;top:17%;width:2px;height:170px;background:#ffd24a;transform:rotate(64deg);transform-origin:top;box-shadow:0 0 8px #ffd24a}.v25-scatter-ray{position:absolute;left:49%;top:50%;height:2px;width:90px;background:#fd8c5a;transform-origin:left;opacity:.75}.v25-sr1{transform:rotate(-42deg)}.v25-sr2{transform:rotate(12deg)}.v25-sr3{transform:rotate(55deg)}.v25-media.playing .v25-scatter-ray{animation:v25scatter 2.4s ease-out infinite}@keyframes v25scatter{0%,35%{width:0;opacity:0}55%{opacity:.85}100%{width:120px;opacity:0}}
.v25-handlab{display:grid;grid-template-columns:260px minmax(0,1fr);gap:18px;padding:18px}.v25-handframe{position:relative;background:#020305;border:1px solid #344054;border-radius:14px;overflow:hidden}.v25-handframe img{width:100%;display:block;transition:filter .12s}.v25-noise{position:absolute;inset:0;pointer-events:none;background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='90' height='90'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.85' numOctaves='2' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='.45'/%3E%3C/svg%3E");mix-blend-mode:screen}.v25-controls label{display:block;margin:0 0 18px}.v25-controls input{width:100%}.v25-readout{border:1px solid #344054;border-radius:12px;padding:12px;margin-top:12px;background:#0b1018}.v25-bars>div{margin:10px 0}.v25-bars span{font-size:.78rem;color:#aab3c2}.v25-meter{height:8px;background:#1d2633;border-radius:10px;overflow:hidden}.v25-meter i{display:block;height:100%;background:linear-gradient(90deg,#9967ff,#d8aa52);width:50%;transition:width .12s}
@media(max-width:760px){.v25-media-head{align-items:flex-start;flex-direction:column}.v25-stage{min-height:300px}.v25-chain{overflow:auto;justify-content:flex-start;padding-bottom:15px}.v25-handlab{grid-template-columns:1fr}.v25-handframe{max-width:330px;margin:auto}.v25-tube{left:3%;right:3%}.v25-label{font-size:.7rem}}
`;
const st=document.createElement('style');st.textContent=styles;document.head.appendChild(st);

function animationType(lesson){
 const t=(lesson.title||'').toLowerCase(),m=lesson.module;
 if(m==='Radiation Physics'){
  if(/brems/.test(t))return 'brems'; if(/characteristic/.test(t))return 'characteristic'; if(/thermionic|filament|cathode|space charge/.test(t))return 'tube'; if(/circuit|transform|rectif|generator/.test(t))return 'circuit'; if(/compton|photoelectric|coherent|interaction|attenuation/.test(t))return 'scatter'; if(/inverse square|distance/.test(t))return 'distance'; return 'tube';
 }
 if(m==='Image Production'){ if(/kvp|mas|technique|receptor exposure|noise/.test(t))return 'hand'; if(/scatter|collimat|grid/.test(t))return 'scatter'; if(/sid|oid|magnif|distort|focal|motion/.test(t))return 'geometry'; return 'hand'; }
 if(m==='Digital Imaging')return /histogram|window|lut|processing/.test(t)?'processing':'detector';
 if(m==='Fluoroscopy')return /scatter|geometry|c-arm|dose/.test(t)?'fluoro':'chain';
 if(m==='Radiation Safety & Biology')return /distance|inverse|scatter|shield|dose/.test(t)?'safety':'chain';
 if(m==='Positioning & Procedures')return 'anatomy';
 if(m==='Patient Care & Clinical')return 'clinical';
 return 'reasoning';
}
function stage(lesson){
 const type=animationType(lesson),t=lesson.title;
 if(type==='circuit') return `<div class="v25-stage" style="display:grid;place-items:center;padding:14px"><img src="assets/v25-approved-circuit-layout.png" alt="Detailed x-ray circuit layout" style="max-width:100%;max-height:315px;object-fit:contain"><div class="v25-caption">${t}: use the labeled circuit to trace the high-voltage pathway and the separate filament pathway. Tap the circuit lab below to study each component.</div></div>`;
 if(type==='tube') return `<div class="v25-stage"><div class="v25-tube"></div><div class="v25-filament"></div><div class="v25-target"></div><i class="v25-electron"></i><i class="v25-electron e2"></i><i class="v25-electron e3"></i><i class="v25-electron e4"></i><i class="v25-photon"></i><span class="v25-label v25-l1">Cathode / filament</span><span class="v25-label v25-l2">Electron acceleration</span><span class="v25-label v25-l3">Anode / photon production</span><div class="v25-caption">${t}: follow the electron source, acceleration, target interaction, and resulting x-ray production.</div></div>`;
 if(type==='brems'||type==='characteristic') return `<div class="v25-stage"><div class="v25-atom"><div class="v25-shell s2"></div><div class="v25-shell"></div><div class="v25-nucleus">W</div><i class="v25-bound v25-b1"></i><i class="v25-bound v25-b2"></i></div><i class="v25-incident"></i><i class="v25-xray"></i><div class="v25-caption">${type==='brems'?'Bremsstrahlung: projectile electron deflects/decelerates in the nuclear electric field; lost kinetic energy is emitted as an x-ray photon.':'Characteristic: projectile electron ejects an inner-shell electron; a higher-shell electron fills the vacancy and the binding-energy difference is emitted as an x-ray photon.'}</div></div>`;
 if(type==='scatter'||type==='fluoro'||type==='safety') return `<div class="v25-stage"><div class="v25-field"><div class="v25-patient"></div><div class="v25-beam"></div><i class="v25-scatter-ray v25-sr1"></i><i class="v25-scatter-ray v25-sr2"></i><i class="v25-scatter-ray v25-sr3"></i></div><div class="v25-caption">${t}: primary photons enter the patient; transmitted, absorbed, and scattered outcomes change image formation and exposure.</div></div>`;
 if(type==='detector') return `<div class="v25-stage"><div class="v25-chain"><div class="v25-box">X-ray photon</div><span class="v25-arrow">→</span><div class="v25-box">Detector conversion</div><span class="v25-arrow">→</span><div class="v25-box">Electrical signal</div><span class="v25-arrow">→</span><div class="v25-box">Readout / ADC</div><span class="v25-arrow">→</span><div class="v25-box">Pixel value</div></div><div class="v25-caption">${t}: trace the information pathway from absorbed x-ray energy to a digital pixel value.</div></div>`;
 if(type==='processing') return `<div class="v25-stage"><div class="v25-chain"><div class="v25-box">Raw detector data</div><span class="v25-arrow">→</span><div class="v25-box">Histogram analysis</div><span class="v25-arrow">→</span><div class="v25-box">LUT / rescaling</div><span class="v25-arrow">→</span><div class="v25-box">Window / level</div><span class="v25-arrow">→</span><div class="v25-box">Displayed image</div></div><div class="v25-caption">${t}: processing changes presentation; it does not undo poor acquisition or change the exposure the patient already received.</div></div>`;
 if(type==='geometry') return `<div class="v25-stage"><div class="v25-chain"><div class="v25-box">Focal spot</div><span class="v25-arrow">→</span><div class="v25-box">SID / OID</div><span class="v25-arrow">→</span><div class="v25-box">Beam divergence</div><span class="v25-arrow">→</span><div class="v25-box">Magnification / blur</div></div><div class="v25-caption">${t}: manipulate the geometry conceptually and connect source, object, detector, magnification, and recorded detail.</div></div>`;
 if(type==='anatomy') { let src=/hand|wrist/.test(t.toLowerCase())?'assets/verified_real/hand-pa-cc0.jpg':/chest/.test(t.toLowerCase())?'assets/verified_real/chest-pa-cc0.jpg':/knee|tibia|fibula/.test(t.toLowerCase())?'assets/verified_real/knee-ap-cc0.jpg':/pelvis|hip/.test(t.toLowerCase())?'assets/verified_real/pelvis-ap-public-domain.jpg':'assets/verified_real/shoulder-y-cc0.jpg'; return `<div class="v25-stage" style="display:grid;place-items:center;padding:16px"><img src="${src}" alt="Radiographic teaching image for ${t}" style="max-height:285px;max-width:88%;object-fit:contain"><div class="v25-caption">${t}: use anatomy inclusion, symmetry, joint spaces, superimposition, and distortion to judge positioning.</div></div>`; }
 const labels=type==='clinical'?['Clinical cue','Safe action','Reassess','Document']:['Read stem','Identify variable','Eliminate distractors','Choose best answer'];
 return `<div class="v25-stage"><div class="v25-chain">${labels.map((x,i)=>`${i?'<span class="v25-arrow">→</span>':''}<div class="v25-box">${x}</div>`).join('')}</div><div class="v25-caption">${t}: work through the sequence and connect each step to the decision that follows.</div></div>`;
}
function handLab(){return `<div class="v25-handlab"><div class="v25-handframe"><img id="v25Hand" src="assets/verified_real/hand-pa-cc0.jpg" alt="PA hand radiograph for live kVp and mAs simulation"><div id="v25Noise" class="v25-noise"></div></div><div class="v25-controls"><label>kVp <strong id="v25KVal">70</strong><input id="v25K" type="range" min="45" max="100" value="70"></label><label>mAs <strong id="v25MVal">5</strong><input id="v25M" type="range" min="1" max="20" step=".5" value="5"></label><div class="v25-bars"><div><span>Penetration / beam quality</span><div class="v25-meter"><i id="v25Energy"></i></div></div><div><span>Relative receptor exposure</span><div class="v25-meter"><i id="v25Exposure"></i></div></div></div><div id="v25Read" class="v25-readout"></div></div></div>`}

const oldMedia=window.v24LessonMedia;
window.v24LessonMedia=function(lesson){
 const lessonAudio=window.V20_AUDIO?.[lesson.id]; const subjAudio=SUBJECT_AUDIO[lesson.module]; const audio=lessonAudio||subjAudio;
 return `<section class="v25-media" data-atype="${animationType(lesson)}"><div class="v25-media-head"><div><span class="premium-label">ANIMATED LESSON</span><h3>${lesson.title}</h3></div><div class="v25-actions">${audio?`<button type="button" class="btn v25-audio">▶ ${lessonAudio?'Play lesson narration':'Play subject narration'}</button>`:''}<button type="button" class="btn btn-secondary v25-play">▶ Run animation</button><button type="button" class="text-btn v25-slow">Slow motion</button></div></div>${animationType(lesson)==='hand'?handLab():stage(lesson)}<div class="v25-legend"><span><i class="v25-dot e"></i>Electron / electrical signal</span><span><i class="v25-dot p"></i>X-ray photon / primary beam</span><span><i class="v25-dot s"></i>Scatter / secondary path</span></div><div class="v25-audio-status" aria-live="polite"></div></section>`;
};

const oldBind=window.bindV24;
window.bindV24=function(lesson){
 oldBind?.(lesson);
 const shell=document.querySelector('.v25-media'); if(!shell)return;
 shell.querySelector('.v25-play')?.addEventListener('click',()=>{shell.classList.remove('playing');void shell.offsetWidth;shell.classList.add('playing')});
 shell.querySelector('.v25-slow')?.addEventListener('click',e=>{shell.classList.toggle('slow');e.currentTarget.textContent=shell.classList.contains('slow')?'Normal speed':'Slow motion'});
 shell.querySelector('.v25-audio')?.addEventListener('click',()=>{const url=window.V20_AUDIO?.[lesson.id]||SUBJECT_AUDIO[lesson.module],s=shell.querySelector('.v25-audio-status');if(!url)return;window.__v25Audio?.pause();const a=new Audio(url);window.__v25Audio=a;s.textContent='Playing natural instructor narration…';a.play().catch(()=>s.textContent='Audio could not start. Tap Play again after the page finishes loading.');a.onended=()=>s.textContent='Narration complete.'});
 const k=document.getElementById('v25K'),m=document.getElementById('v25M');if(k&&m){const update=()=>{const kv=+k.value,ma=+m.value;document.getElementById('v25KVal').textContent=kv;document.getElementById('v25MVal').textContent=ma;const ex=(ma/5)*Math.pow(kv/70,2),kn=(kv-45)/55;const img=document.getElementById('v25Hand'),noise=document.getElementById('v25Noise');img.style.filter=`brightness(${.86+Math.min(1.4,ex)*.12}) contrast(${1.42-kn*.55})`;noise.style.opacity=String(Math.max(.03,Math.min(.72,.68/Math.sqrt(Math.max(.15,ex))-.18)));document.getElementById('v25Energy').style.width=`${Math.max(4,kn*100)}%`;document.getElementById('v25Exposure').style.width=`${Math.max(4,Math.min(100,ex*55))}%`;document.getElementById('v25Read').innerHTML=`<b>${kv<60?'Low penetration':kv>84?'High penetration':'Moderate penetration'}</b><br>Relative receptor exposure: ${ex.toFixed(2)}×<br>Quantum-noise risk: ${ex<.65?'HIGH':ex<1.25?'MODERATE':'LOW'}<br><small>Digital processing can normalize brightness, so the simulator emphasizes penetration, exposure and noise—not film-screen brightness.</small>`};k.addEventListener('input',update);m.addEventListener('input',update);update();}
};

// Expand short lessons with a consistent deep-learning structure without generic learner-language prompts.
courseData.forEach(mod=>{
  const ls=mod.lessons;
  ls.forEach((lesson,idx)=>{
    // Remove rejected prediction/reflection filler from older builds.
    lesson.content=(lesson.content||'')
      .replace(/<h3>Think before you click<\/h3>[\s\S]*?<\/div>/gi,'')
      .replace(/<div class=\"concept-check\">[\s\S]*?<\/div>/gi,'')
      .replace(/Predict the result first\.[^<]*/gi,'')
      .replace(/Make a prediction[^<]*/gi,'');
    // Replace generic learner/meta questions with direct concept-discrimination questions.
    const distractorSummaries=[1,2,3].map(off=>ls[(idx+off)%ls.length].summary);
    const correct=lesson.summary;
    const stems=[
      `Which statement most accurately describes ${lesson.title}?`,
      `Which explanation best matches the mechanism emphasized in ${lesson.title}?`,
      `Which statement is most specific to ${lesson.title}?`,
      `Which description should be associated with ${lesson.title}?`,
      `Which statement best distinguishes ${lesson.title} from the other concepts in this section?`
    ];
    lesson.check=stems.map((q,qi)=>{
      const pool=[correct,...distractorSummaries];
      const rot=qi%4;
      const options=pool.slice(rot).concat(pool.slice(0,rot));
      return {q,options,answer:options.indexOf(correct),rationale:`${correct} The other choices describe related concepts from the same subject, which is why they are plausible distractors but do not match this specific topic.`};
    });
 const text=(lesson.content||'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
 if(text.length<1500){
   lesson.content += `<section class="v25-deep"><h3>Mechanism and clinical reasoning</h3><p><strong>${lesson.title}</strong> should be understood as a cause-and-effect pathway. Identify the controlling component, physical or clinical mechanism, and the consequence that follows. Use the animation above to trace that pathway before memorizing terminology.</p><h3>What changes — and what does not</h3><p>Separate variables that affect x-ray production, patient attenuation, geometry, detector exposure, image processing, dose, positioning, or patient care. Similar-looking outcomes may have different causes, which is why registry questions often use plausible distractors.</p><h3>Image / clinical connection</h3><p>Apply the concept to the examination workflow: predict what would change on the image or at the detector, what would change for the patient or technologist, and what correction would address the actual cause rather than merely changing appearance.</p><h3>Registry trap</h3><p>Do not choose an answer because it is generally related to the topic. Choose the option that matches the specific mechanism and the variable named in the question stem.</p></section>`;
 }
  });
});
})();
