(function(){
const css=`
.anatomy-summary{display:flex;gap:8px;align-items:baseline}.anatomy-summary strong{font-size:1.6rem;color:#d8aa52}.anatomy-summary span{font-size:.78rem;color:#9aa4b2}.anatomy-category-bar,.anatomy-mode-bar{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}.anatomy-category-bar button{border:1px solid #384456;background:#0f151e;color:#dce3ec;padding:10px 14px;border-radius:999px}.anatomy-category-bar button.active{border-color:#d8aa52;color:#fff;background:#1b1710}.anatomy-workbench{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(280px,.65fr);gap:18px}.anatomy-image-card,.anatomy-info-card{background:#0d121a;border:1px solid #2c3747;border-radius:18px;padding:16px}.anatomy-image-wrap{position:relative;display:grid;place-items:center;background:#020305;border-radius:14px;min-height:480px;overflow:hidden}.anatomy-image-wrap img{max-height:620px;max-width:100%;object-fit:contain;display:block}.anatomy-hotspot{position:absolute;width:28px;height:28px;border-radius:50%;border:2px solid #fff;background:rgba(151,98,255,.78);box-shadow:0 0 0 5px rgba(151,98,255,.18);transform:translate(-50%,-50%);cursor:pointer}.anatomy-hotspot.learn::after{content:attr(data-label);position:absolute;left:34px;top:50%;transform:translateY(-50%);white-space:nowrap;background:#111722;border:1px solid #39485c;border-radius:8px;padding:4px 7px;font-size:.72rem;color:#fff}.anatomy-prompt{padding:14px;border-radius:12px;background:#111722;border:1px solid #2f3b4d;margin:12px 0}.anatomy-feedback{min-height:48px;padding:12px;border-radius:12px;background:#0a0f16;border:1px solid #263142}.anatomy-feedback.ok{border-color:#3d9c6e;color:#a6efc8}.anatomy-feedback.bad{border-color:#b45a5a;color:#ffb4b4}.anatomy-label-list{display:flex;gap:8px;flex-wrap:wrap}.anatomy-label-chip{border:1px solid #3a4657;border-radius:10px;padding:8px 10px;background:#111722;color:#fff}.anatomy-score-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin-top:14px}.anatomy-score-grid div{padding:10px;border:1px solid #2d3848;border-radius:10px}.lesson-reader{scroll-margin-top:90px}.lesson-card button,.lesson-open-link{text-decoration:underline;text-underline-offset:4px}.v26-complete{display:flex;align-items:center;gap:10px;padding:12px;border:1px solid #344054;border-radius:12px;margin:14px 0;background:#0b1119}.v26-complete input{width:20px;height:20px}.v26-audio-segment{margin-top:10px;color:#aeb7c5;font-size:.82rem}.v26-strengths{display:grid;grid-template-columns:1fr 1fr;gap:12px}.v26-strengths article{padding:14px;border:1px solid #2f3b4d;border-radius:12px}.v26-strengths strong{display:block;font-size:1.2rem}.v26-title-path{font-size:.82rem;color:#d8aa52;text-decoration:underline;text-underline-offset:4px}
.v26-lab{margin:14px 18px 18px;padding:14px;border:1px solid #344054;border-radius:14px;background:#0b1119}.v26-lab strong{display:block;margin-bottom:10px}.v26-lab label{display:block;margin:10px 0}.v26-lab input{width:100%}.v26-lab p{margin:8px 0 0;color:#c8d0da;font-size:.88rem}@media(max-width:850px){.anatomy-workbench{grid-template-columns:1fr}.anatomy-image-wrap{min-height:360px}.anatomy-hotspot.learn::after{font-size:.64rem;max-width:110px;white-space:normal}.v26-strengths{grid-template-columns:1fr}}
`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);

const CASES={
 'Chest':{img:'assets/verified_real/chest-pa-cc0.jpg',title:'PA Chest',structures:[['Trachea',50,16,'Midline air column superior to the carina.'],['Carina',50,34,'Bifurcation of the trachea into main bronchi.'],['Right costophrenic angle',26,86,'Acute lateral angle where diaphragm meets chest wall.'],['Left costophrenic angle',75,86,'Acute lateral angle where diaphragm meets chest wall.'],['Right hemidiaphragm',39,79,'Usually slightly higher than the left.'],['Heart border',61,60,'Cardiac silhouette should not be magnified on a properly positioned PA chest.']],critique:[['Which finding best supports a nonrotated PA chest?',['Clavicles are above the apices','SC joints are equidistant from the vertebral column','Ten posterior ribs are always visible','Heart is centered on the spine'],1,'Rotation is assessed by symmetry of the sternoclavicular joints relative to the vertebral column.'],['What positioning feature most reduces cardiac magnification?',['AP projection','Short SID','PA projection with long SID','Lordotic position'],2,'PA projection and long SID reduce cardiac magnification.']]},
 'Hand':{img:'assets/verified_real/hand-pa-cc0.jpg',title:'PA Hand',structures:[['Distal radius',38,84,'Broad distal forearm bone on the thumb side.'],['Distal ulna',62,85,'Medial distal forearm bone.'],['Carpals',49,70,'Eight small wrist bones between forearm and metacarpals.'],['3rd metacarpal',50,53,'Central metacarpal aligned with the middle finger.'],['PIP joint',49,30,'Joint between proximal and middle phalanges.']],critique:[['Which feature best indicates a true PA hand?',['Digits are fully flexed','Metacarpal heads show symmetric concavity and minimal rotation','Thumb is superimposed on palm','Wrist is excluded'],1,'A true PA hand minimizes rotation and preserves symmetric metacarpal relationships.']]},
 'Knee':{img:'assets/verified_real/knee-ap-cc0.jpg',title:'AP Knee',structures:[['Medial femoral condyle',43,27,'Medial distal femoral condyle.'],['Lateral femoral condyle',60,27,'Lateral distal femoral condyle.'],['Tibial plateau',51,48,'Proximal articular surface of the tibia.'],['Fibular head',73,57,'Proximal fibula; partly superimposed on the tibia on a correctly positioned AP knee.'],['Intercondylar eminence',51,43,'Tibial spines between the plateaus.']],critique:[['On an AP knee, excessive fibular-head superimposition most strongly suggests:',['Too much medial rotation','Too much lateral rotation','Excessive knee flexion','Insufficient SID'],0,'Medial rotation increases superimposition of the fibular head by the tibia.']]},
 'Foot':{img:'assets/verified_real/foot-ap-cc0.jpg',title:'AP/Dorsoplantar Foot',structures:[['Calcaneus',23,78,'Largest tarsal bone forming the heel.'],['Talus',34,66,'Tarsal bone articulating with tibia and fibula.'],['Navicular',44,62,'Medial tarsal between talus and cuneiforms.'],['1st metatarsal',60,50,'Metatarsal leading to the great toe.'],['5th metatarsal base',65,66,'Lateral metatarsal base, common fracture site.']],critique:[['Which adjustment best opens the tarsometatarsal joint spaces on an AP foot?',['Angle CR 10° toward heel','Angle CR 20° toward toes','Use 72-inch SID','Externally rotate the foot 45°'],0,'A modest posterior angle toward the heel helps align the beam with the metatarsal bases.']]},
 'Pelvis/Hip':{img:'assets/verified_real/pelvis-ap-public-domain.jpg',title:'AP Pelvis',structures:[['Acetabulum',34,57,'Cup-shaped socket of the hip joint.'],['Femoral head',34,64,'Rounded proximal femur articulating with acetabulum.'],['Obturator foramen',44,72,'Large opening formed by pubis and ischium.'],['Iliac crest',28,26,'Superior border of ilium.'],['Pubic symphysis',50,81,'Midline cartilaginous joint of the pubic bones.']],critique:[['Which finding best indicates pelvic rotation?',['Symmetric iliac wings and obturator foramina','Asymmetric iliac wings and obturator foramina','Lesser trochanters minimally visible bilaterally','Sacrum aligned with symphysis'],1,'Pelvic rotation changes the symmetry of the iliac wings and obturator foramina.']]},
 'Shoulder':{img:'assets/verified_real/shoulder-y-cc0.jpg',title:'Scapular Y',structures:[['Acromion',57,28,'Posterior-superior process of scapula.'],['Coracoid',43,38,'Anterior scapular process.'],['Glenoid',50,48,'Shallow socket for humeral head.'],['Humeral head',51,51,'Should project over the glenoid on a normal scapular Y.'],['Scapular body',51,70,'Body of the scapula forming the stem of the Y.']],critique:[['In a normal scapular Y, the humeral head should project:',['Over the acromion','Over the coracoid','Over the glenoid at the center of the Y','Below the inferior angle'],2,'The humeral head should be centered over the glenoid at the Y intersection.']]}
};
CASES['Abdomen']={img:'https://upload.wikimedia.org/wikipedia/commons/8/8f/Hirschsprungs.jpg',title:'Abdominal radiograph / contrast study',structures:[['Right abdomen',37,48,'Evaluate bowel gas pattern, soft-tissue margins, and coverage.'],['Left abdomen',63,48,'Compare distribution and symmetry across the abdomen.'],['Pelvic cavity',50,78,'Lower abdominal and pelvic anatomy should be included when the projection requires it.']],critique:[['For a routine supine AP abdomen, which anatomy is generally most important to include?',['Only the diaphragm','Kidneys through symphysis pubis as required by protocol','Only the iliac crests','Only the stomach'],1,'Coverage should include the required abdominal anatomy; exact centering depends on the requested projection and indication.']]};
CASES['Spine']={img:'https://upload.wikimedia.org/wikipedia/commons/1/14/Ankylosing_spondylitis_lumbar_spine.jpg',title:'Lateral Lumbar Spine',structures:[['L1 body',51,22,'Upper lumbar vertebral body.'],['L3 body',51,48,'Mid-lumbar vertebral body.'],['L5 body',52,72,'Lowest lumbar vertebral body above the sacrum.'],['L5-S1 space',54,80,'Lumbosacral intervertebral disc space.']],critique:[['Which factor most directly improves visualization of intervertebral spaces on a lateral lumbar spine?',['True lateral positioning with appropriate centering','Increasing OID','Rotating the patient 45 degrees','Using a shorter SID'],0,'True lateral alignment and correct centering are essential before technique changes are considered.']]};
CASES['Skull/Facial']={img:'https://upload.wikimedia.org/wikipedia/commons/9/9c/Skull_Fracture_X-ray.jpeg',title:'Lateral Skull',structures:[['Frontal bone',62,23,'Anterior cranial vault.'],['Parietal region',45,22,'Superior-lateral cranial vault.'],['Sella region',54,50,'Central skull-base landmark in the sphenoid region.'],['Mandible',65,76,'Lower jaw seen in profile.']],critique:[['A true lateral skull should demonstrate:',['Superimposed orbital roofs and mandibular rami as closely as possible','Open intervertebral foramina','Symmetric obturator foramina','A free lesser trochanter'],0,'Superimposition of paired cranial structures is a key lateral-skull evaluation criterion.']]};
CASES['Contrast/Fluoro']={img:'https://upload.wikimedia.org/wikipedia/commons/f/f8/ContrastDetailImage.jpg',title:'Fluoroscopy Contrast-Detail Phantom',structures:[['High-contrast target',23,33,'Larger, more visible target used to assess contrast-detail performance.'],['Lower-contrast targets',42,55,'Smaller or lower-contrast objects become harder to visualize as contrast and size decrease.'],['Background field',70,60,'Uniform background permits comparison of target visibility.']],critique:[['What does a contrast-detail phantom primarily evaluate?',['Only spatial resolution at high contrast','The relationship between object size and detectable contrast','Patient positioning accuracy','X-ray tube focal spot angle only'],1,'Contrast-detail phantoms assess detectability across combinations of object size and contrast.']]};

const state={cat:'Chest',mode:'learn',target:0,challenge:[],challengeIndex:0,challengeScore:0};
const saved=JSON.parse(localStorage.getItem('rmAnatomyV26')||'{}');
function saveAnatomy(){localStorage.setItem('rmAnatomyV26',JSON.stringify(saved));updateMastery();}
function updateMastery(){const vals=Object.values(saved);const pct=vals.length?Math.round(vals.reduce((a,b)=>a+b,0)/vals.length):0;const el=document.getElementById('anatomyMastery');if(el)el.textContent=pct+'%';}
function makeHotspots(c,showLabels=false){return c.structures.map((x,i)=>`<button class="anatomy-hotspot ${showLabels?'learn':''}" style="left:${x[1]}%;top:${x[2]}%" data-idx="${i}" data-label="${x[0]}" aria-label="${x[0]}"></button>`).join('')}
function scoreCat(delta){saved[state.cat]=Math.max(0,Math.min(100,(saved[state.cat]||0)+delta));saveAnatomy()}
function renderAnatomy(){const wb=document.getElementById('anatomyWorkbench');if(!wb)return;const c=CASES[state.cat];document.querySelectorAll('#anatomyCategories button').forEach(b=>b.classList.toggle('active',b.dataset.cat===state.cat));document.querySelectorAll('#anatomyModes button').forEach(b=>b.classList.toggle('active',b.dataset.anatomyMode===state.mode));
 if(state.mode==='learn'){wb.innerHTML=`<article class="anatomy-image-card"><div class="anatomy-image-wrap"><img src="${c.img}" alt="${c.title}">${makeHotspots(c,true)}</div></article><aside class="anatomy-info-card"><p class="eyebrow">Learn mode</p><h3>${c.title}</h3><p>Tap a labeled structure to review how to recognize it on the radiograph.</p><div id="anatomyFeedback" class="anatomy-feedback">Choose a structure.</div><div class="anatomy-score-grid"><div><span>Current category mastery</span><strong>${saved[state.cat]||0}%</strong></div><div><span>Structures</span><strong>${c.structures.length}</strong></div></div></aside>`;}
 if(state.mode==='identify'){state.target=Math.floor(Math.random()*c.structures.length);wb.innerHTML=`<article class="anatomy-image-card"><div class="anatomy-image-wrap"><img src="${c.img}" alt="${c.title}">${makeHotspots(c,false)}</div></article><aside class="anatomy-info-card"><p class="eyebrow">Identify mode</p><h3>Find: ${c.structures[state.target][0]}</h3><div class="anatomy-prompt">Tap the correct location on the radiograph.</div><div id="anatomyFeedback" class="anatomy-feedback">Waiting for your selection.</div><button class="btn" id="nextIdentify">New structure</button></aside>`;}
 if(state.mode==='label'){wb.innerHTML=`<article class="anatomy-image-card"><div class="anatomy-image-wrap"><img src="${c.img}" alt="${c.title}">${makeHotspots(c,false)}</div></article><aside class="anatomy-info-card"><p class="eyebrow">Label mode</p><h3>Match labels to anatomy</h3><p>Select a label, then tap its location.</p><div class="anatomy-label-list">${c.structures.map((x,i)=>`<button class="anatomy-label-chip" data-labelidx="${i}">${x[0]}</button>`).join('')}</div><div id="anatomyFeedback" class="anatomy-feedback">Choose a label first.</div></aside>`;state.target=-1;}
 if(state.mode==='critique'){const q=c.critique[0];wb.innerHTML=`<article class="anatomy-image-card"><div class="anatomy-image-wrap"><img src="${c.img}" alt="${c.title}"></div></article><aside class="anatomy-info-card"><p class="eyebrow">Image critique</p><h3>${c.title}</h3><div class="anatomy-prompt">${q[0]}</div><div class="answer-list">${q[1].map((x,i)=>`<button class="answer-btn" data-crit="${i}">${x}</button>`).join('')}</div><div id="anatomyFeedback" class="anatomy-feedback"></div></aside>`;}
 if(state.mode==='challenge'){if(!state.challenge.length){state.challenge=[];Object.entries(CASES).forEach(([cat,cc])=>cc.structures.slice(0,2).forEach((s,i)=>state.challenge.push({cat,idx:i})));state.challenge.sort(()=>Math.random()-.5);state.challengeIndex=0;state.challengeScore=0;}const q=state.challenge[state.challengeIndex];const qc=CASES[q.cat];wb.innerHTML=`<article class="anatomy-image-card"><div class="anatomy-image-wrap"><img src="${qc.img}" alt="${qc.title}">${makeHotspots(qc,false)}</div></article><aside class="anatomy-info-card"><p class="eyebrow">Timed challenge</p><h3>${state.challengeIndex+1}/${state.challenge.length}: Find ${qc.structures[q.idx][0]}</h3><p>Score: ${state.challengeScore}</p><div id="anatomyFeedback" class="anatomy-feedback">Tap the structure.</div></aside>`;state.target=q.idx;}
 bindAnatomy();updateMastery();}
function bindAnatomy(){document.querySelectorAll('.anatomy-hotspot').forEach(b=>b.onclick=()=>{const idx=+b.dataset.idx,c=CASES[state.mode==='challenge'?state.challenge[state.challengeIndex].cat:state.cat],fb=document.getElementById('anatomyFeedback');if(state.mode==='learn'){fb.innerHTML=`<strong>${c.structures[idx][0]}</strong><br>${c.structures[idx][3]}`;return;}if(state.mode==='label'&&state.target<0){fb.textContent='Choose a label first.';return;}const target=state.mode==='label'?state.target:state.target;const ok=idx===target;fb.className='anatomy-feedback '+(ok?'ok':'bad');fb.innerHTML=ok?`Correct — ${c.structures[target][0]}. ${c.structures[target][3]}`:`Not quite. You selected ${c.structures[idx][0]}. Recheck the landmarks.`;if(ok){scoreCat(4);if(state.mode==='challenge'){state.challengeScore++;setTimeout(()=>{state.challengeIndex++;if(state.challengeIndex>=state.challenge.length){document.getElementById('anatomyWorkbench').innerHTML=`<article class="anatomy-info-card"><p class="eyebrow">Challenge complete</p><h3>${state.challengeScore}/${state.challenge.length}</h3><p>Your anatomy performance has been added to mastery tracking.</p><button class="btn" id="restartAnatomyChallenge">Run another challenge</button></article>`;document.getElementById('restartAnatomyChallenge').onclick=()=>{state.challenge=[];renderAnatomy()};}else renderAnatomy();},550)}}else scoreCat(-1)});document.querySelectorAll('[data-labelidx]').forEach(b=>b.onclick=()=>{state.target=+b.dataset.labelidx;document.getElementById('anatomyFeedback').textContent=`Now tap ${CASES[state.cat].structures[state.target][0]} on the image.`});document.querySelectorAll('[data-crit]').forEach(b=>b.onclick=()=>{const q=CASES[state.cat].critique[0],ok=+b.dataset.crit===q[2],fb=document.getElementById('anatomyFeedback');fb.className='anatomy-feedback '+(ok?'ok':'bad');fb.textContent=(ok?'Correct. ':'Review this. ')+q[3];scoreCat(ok?5:-1)});document.getElementById('nextIdentify')?.addEventListener('click',()=>renderAnatomy());}
function initAnatomy(){const cats=document.getElementById('anatomyCategories');if(!cats)return;cats.innerHTML=Object.keys(CASES).map((c,i)=>`<button data-cat="${c}" class="${i===0?'active':''}">${c}</button>`).join('');cats.querySelectorAll('button').forEach(b=>b.onclick=()=>{state.cat=b.dataset.cat;state.challenge=[];renderAnatomy()});document.querySelectorAll('[data-anatomy-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.anatomyMode;state.challenge=[];renderAnatomy()});renderAnatomy();}

// Make the overview Anatomy entry open the dedicated lab, not a hidden inline widget.
document.getElementById('openAnatomyLab')?.addEventListener('click',e=>{e.preventDefault();document.querySelector('[data-view="anatomy"]')?.click()});

// Add reviewed tracking and a visible path cue to every opened lesson.
const origBind=window.bindV24;
if(origBind){window.bindV24=function(lesson){origBind(lesson);setTimeout(()=>{const r=document.getElementById('lessonReader');if(!r)return;let bar=r.querySelector('.v26-complete');if(!bar){bar=document.createElement('label');bar.className='v26-complete';bar.innerHTML=`<input type="checkbox" id="v26Reviewed"><span><strong>Mark this lesson reviewed</strong><br><small>This records that you completed the teaching content. Quiz score is tracked separately.</small></span>`;r.insertBefore(bar,r.querySelector('.lesson-check')||r.lastChild)}const key='rmReviewed:'+lesson.id,cb=document.getElementById('v26Reviewed');cb.checked=localStorage.getItem(key)==='1';cb.onchange=()=>localStorage.setItem(key,cb.checked?'1':'0');r.scrollIntoView({block:'start',behavior:'smooth'});},0)}}

// Rename the test banner and strengthen path affordances in lesson list after each render.
const mo=new MutationObserver(()=>{document.querySelectorAll('.lesson-item,.lesson-card').forEach(el=>{if(!el.querySelector('.v26-title-path')){const h=el.querySelector('h3,strong');if(h){const p=document.createElement('span');p.className='v26-title-path';p.textContent='Open this topic →';el.appendChild(p)}}})});
const ll=document.getElementById('lessonList');if(ll)mo.observe(ll,{childList:true,subtree:true});

// Strong/weak summary from stored quiz/anatomy signals.
function masterySummary(){const panel=document.querySelector('.dashboard-grid .panel:nth-child(2)');if(!panel)return;const anatomyVals=Object.entries(saved).map(([k,v])=>({k:'Anatomy: '+k,v}));let st={};try{st=JSON.parse(localStorage.getItem('rrm-state')||'{}')}catch(e){}const scores=st.masteryScores||{};const lessonScores=Object.entries(scores).map(([id,v])=>{const l=courseData.flatMap(m=>m.lessons).find(x=>x.id===id);return {k:l?l.title:id,v:Math.round((+v/5)*100)}});const all=[...anatomyVals,...lessonScores].sort((a,b)=>a.v-b.v);if(!all.length)return;const weak=all.slice(0,3),strong=all.slice(-3).reverse();panel.innerHTML=`<div class="panel-header"><div><small>Adaptive mastery</small><h3>Strong & weak areas</h3></div></div><div class="v26-strengths"><article><span>Needs study</span>${weak.map(x=>`<strong>${x.v}%</strong><small>${x.k}</small>`).join('<hr>')}</article><article><span>Strong areas</span>${strong.map(x=>`<strong>${x.v}%</strong><small>${x.k}</small>`).join('<hr>')}</article></div>`}
setTimeout(()=>{initAnatomy();updateMastery();masterySummary()},250);


// V26 lesson-specific natural narration segments.
// Each subject master contains 20 lesson-specific narrations in sequence; playback slices the master into 20 module tracks.
const V26_AUDIO_MASTERS={
 'Radiation Physics':'https://www.aidocmaker.com/g0/audio?name=0f40abace92b47c0bc0830b0f12baa74',
 'Image Production':'https://www.aidocmaker.com/g0/audio?name=b8f2d97ea41349b2935b9555bef321c5',
 'Digital Imaging':'https://www.aidocmaker.com/g0/audio?name=5bc82304752541999914add75a613848',
 'Fluoroscopy':'https://www.aidocmaker.com/g0/audio?name=8505decc78c94d2993b287c7e6978e53',
 'Radiation Safety & Biology':'https://www.aidocmaker.com/g0/audio?name=c8ec55c862b64a63b14e007734a98b37',
 'Patient Care & Clinical':'https://www.aidocmaker.com/g0/audio?name=68d589c4bff24c1d8ad6b63fe18586a0',
 'Positioning & Procedures':'https://www.aidocmaker.com/g0/audio?name=c71ed0120af44545a9074c2c125185ee',
 'Registry Strategy':'https://www.aidocmaker.com/g0/audio?name=72b5f7368c014f0693c462e60507e368'
};
window.V26_AUDIO_MASTERS=V26_AUDIO_MASTERS;
function lessonIndex(lesson){const m=courseData.find(x=>x.module===lesson.module);return Math.max(0,m?m.lessons.findIndex(x=>x.id===lesson.id):0)}
function attachV26Audio(lesson,shell){const btn=shell?.querySelector('.v25-audio');if(!btn)return;const dedicated=window.V20_AUDIO?.[lesson.id];if(dedicated){btn.textContent='▶ Play lesson narration';return;}const master=V26_AUDIO_MASTERS[lesson.module];if(!master)return;const repl=btn.cloneNode(true);btn.replaceWith(repl);repl.textContent='▶ Play lesson narration';repl.onclick=()=>{window.__v26Audio?.pause();const a=new Audio(master);window.__v26Audio=a;const status=shell.querySelector('.v25-audio-status');const idx=lessonIndex(lesson);status.textContent=`Loading lesson ${idx+1} narration…`;a.addEventListener('loadedmetadata',()=>{const slice=a.duration/20;const start=slice*idx+.15,end=Math.min(a.duration,slice*(idx+1)-.15);a.currentTime=start;a.play().then(()=>status.textContent='Playing natural male instructor narration…').catch(()=>status.textContent='Tap Play again after audio loads.');const stop=()=>{if(a.currentTime>=end){a.pause();a.removeEventListener('timeupdate',stop);status.textContent='Lesson narration complete.'}};a.addEventListener('timeupdate',stop)},{once:true});a.addEventListener('error',()=>status.textContent='Narration could not load. Check internet connection and retry.');};}

function controlMarkup(type){
 if(type==='tube') return `<div class="v26-lab"><strong>Tube controls</strong><label>Filament heating <span id="v26FilVal">50%</span><input id="v26Fil" type="range" min="10" max="100" value="50"></label><label>kVp <span id="v26TubeKVal">70</span><input id="v26TubeK" type="range" min="40" max="120" value="70"></label><p id="v26TubeOut"></p></div>`;
 if(type==='scatter'||type==='safety'||type==='fluoro') return `<div class="v26-lab"><strong>Scatter / field interaction</strong><label>Field size <span id="v26FieldVal">50%</span><input id="v26Field" type="range" min="15" max="100" value="50"></label><label>Distance from patient <span id="v26DistVal">1.0 m</span><input id="v26Dist" type="range" min="50" max="250" value="100"></label><p id="v26ScatterOut"></p></div>`;
 if(type==='geometry') return `<div class="v26-lab"><strong>Geometry lab</strong><label>SID <span id="v26SidVal">40 in</span><input id="v26Sid" type="range" min="32" max="72" step="1" value="40"></label><label>OID <span id="v26OidVal">2 in</span><input id="v26Oid" type="range" min="0" max="12" step="0.5" value="2"></label><p id="v26GeomOut"></p></div>`;
 if(type==='detector'||type==='processing'||type==='chain') return `<div class="v26-lab"><strong>Digital signal lab</strong><label>Detector exposure <span id="v26DetVal">100%</span><input id="v26Det" type="range" min="20" max="200" value="100"></label><p id="v26DetOut"></p></div>`;
 return '';
}
function attachV26Controls(lesson,shell){if(!shell)return;const type=shell.dataset.atype;const m=controlMarkup(type);if(!m)return;let lab=shell.querySelector('.v26-lab');if(!lab){shell.insertAdjacentHTML('beforeend',m);lab=shell.querySelector('.v26-lab')}
 const fil=document.getElementById('v26Fil'),tk=document.getElementById('v26TubeK');if(fil&&tk){const u=()=>{const f=+fil.value,k=+tk.value;document.getElementById('v26FilVal').textContent=f+'%';document.getElementById('v26TubeKVal').textContent=k;const dots=shell.querySelectorAll('.v25-electron');dots.forEach((d,i)=>{d.style.boxShadow=`0 0 ${8+f/4}px #55a7ff`;d.style.opacity=String(.25+f/135)});const fp=shell.querySelector('.v25-filament');if(fp){fp.style.boxShadow=`0 0 ${8+f/2}px #ff7a20`;fp.style.filter=`brightness(${.65+f/65})`;}document.getElementById('v26TubeOut').innerHTML=`Electron availability: <b>${f<35?'low':f>75?'high':'moderate'}</b>. Electron kinetic-energy ceiling: <b>${k} keV</b>. Raising filament heating mainly changes electron availability; raising kVp increases acceleration energy.`};fil.oninput=u;tk.oninput=u;u();}
 const fs=document.getElementById('v26Field'),ds=document.getElementById('v26Dist');if(fs&&ds){const u=()=>{const f=+fs.value,d=+ds.value/100;document.getElementById('v26FieldVal').textContent=f+'%';document.getElementById('v26DistVal').textContent=d.toFixed(2)+' m';shell.querySelectorAll('.v25-scatter-ray').forEach((r,i)=>{r.style.width=(25+f*(.55+i*.08))+'px';r.style.opacity=String(.15+f/150)});const rel=(1/(d*d));document.getElementById('v26ScatterOut').innerHTML=`Larger field → <b>more scatter</b>. Relative scatter exposure at ${d.toFixed(2)} m ≈ <b>${rel.toFixed(2)}×</b> the 1-meter reference.`};fs.oninput=u;ds.oninput=u;u();}
 const sid=document.getElementById('v26Sid'),oid=document.getElementById('v26Oid');if(sid&&oid){const u=()=>{const s=+sid.value,o=+oid.value,sod=Math.max(0.5,s-o),mag=s/sod;const fmt=n=>Number.isInteger(n)?String(n):n.toFixed(1);document.getElementById('v26SidVal').textContent=fmt(s)+' in';document.getElementById('v26OidVal').textContent=fmt(o)+' in';document.getElementById('v26GeomOut').innerHTML=`SOD: <b>${fmt(sod)} in</b>. Magnification factor ≈ <b>${mag.toFixed(2)}×</b>. Increasing OID increases magnification; increasing SID reduces it when OID is unchanged.`};sid.oninput=u;oid.oninput=u;u();}
 const det=document.getElementById('v26Det');if(det){const u=()=>{const v=+det.value;document.getElementById('v26DetVal').textContent=v+'%';document.getElementById('v26DetOut').innerHTML=`Relative signal: <b>${(v/100).toFixed(2)}×</b>. Quantum-noise tendency: <b>${v<60?'high':v<110?'moderate':'lower'}</b>. Digital processing can change presentation, but it does not erase underexposure noise or patient dose.`};det.oninput=u;u();}}

const prevBindV26=window.bindV24;
if(prevBindV26){window.bindV24=function(lesson){prevBindV26(lesson);setTimeout(()=>{const shell=document.querySelector('.v25-media');attachV26Audio(lesson,shell);attachV26Controls(lesson,shell);},0)}}

})();
